# Generated by Django 3.2.21 on 2023-10-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_slot_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='content',
            new_name='size',
        ),
    ]
