# Generated by Django 3.2.21 on 2023-11-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_content_slot_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
    ]
